config:
  environment:
    time: 1000
    difficulty: HARD
  runner:
    helmet: LEATHER_HELMET
    chestplate: LEATHER_CHESTPLATE
    leggings: LEATHER_LEGGINGS
    boots: LEATHER_BOOTS
    items:
      - WOODEN_AXE
      - OAK_LOG 5
      - COOKED_BEEF 2
  hunter:
    helmet: null
    chestplate: null
    leggings: null
    boots: null
    items:
      - COMPASS
    waiting_time: 15
  game:
    max_health: 20
    enable_compass: true
    clear_advancement: true
    gamemode: SURVIVAL
string:
  runner_start_msg: You are Runner. RUN!
  runner_hunting_start_msg: Hunters start hunting now.
  hunter_start_msg: You are hunter, please wait for $sec$s.
  set_runner: $p$ is set to be Runner.
  cannot_find_player: Cannot find player $p$.
  win: You Win
  lose: You Lose
  runner_dead: Runner is killed
  runner_enter_nether: Runner Entered Nether
  compass_swap: Swap compass to the last item on the hotbar
  err:
    change_runner_in_game: Cannot change runner during game.
    runner_empty: Please set the runner first.
    game_running: Hunting Game is already running.
    compass_add: Cannot get the compass. Inventory is full.