config:
  environment:
    time: 1000
    difficulty: HARD
  runner:
    helmet: LEATHER_HELMET
    chestplate: LEATHER_CHESTPLATE
    leggings: LEATHER_LEGGINGS
    boots: LEATHER_BOOTS
    items:
      - WOODEN_AXE
      - OAK_LOG 5
      - COOKED_BEEF 2
  hunter:
    helmet: null
    chestplate: null
    leggings: null
    boots: null
    items:
      - COMPASS
    waitting_time: 15
  game:
    enable_compass: true
    clear_advancement: true
    gamemode: SURVIVAL