# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        dependency-graph: generate-and-submit
        artifact-retention-days: 7
    - name: Build with Gradle
      run: ./gradlew jar
    - name: Push release
      run: |
        cd build/libs || exit 1
        git init
        git config --local user.name "github-actions"
        git config --local user.email "41898282+github-actions@users.noreply.github.com"
        git checkout -b release
        git add .
        git commit -m "Publish Release for $GITHUB_SHA"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin release


  minecraft-test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: release
          path: plugins
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Download PaperUpdater
        uses: robinraju/release-downloader@v1.8
        with:
          repository: XZTDean/PaperUpdater
          latest: true
          fileName: "PaperUpdater*.jar"
      - name: Download minecraft new build
        run: java -jar -Xms1G -Xmx1G PaperUpdater*.jar
      - name: Download StopServer plugins
        uses: robinraju/release-downloader@v1.8
        with:
          repository: XZTDean/MinecraftStopServer
          latest: true
          fileName: "StopServer*.jar"
          out-file-path: "plugins"
      - name: Agree eula
        run: echo "eula=true" > eula.txt
      - name: Run the game
        run: java -Xms4G -Xmx6G -jar paper.jar --nogui
      - name: Check error in logs
        run: if grep "Could not load 'plugins" logs/latest.log || grep "Error occurred while enabling UHC" logs/latest.log; then exit 1; fi
