# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Push release
      run: |
        cd build/libs || exit 1
        git init
        git config --local user.name "github-actions"
        git config --local user.email "41898282+github-actions@users.noreply.github.com"
        git checkout -b release
        git add .
        git commit -m "Release file"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin release


  minecraft-test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: release
          path: manhunt
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Download minecraft new build
        run: wget -q https://papermc.io/api/v2/projects/paper/versions/1.18.1/builds/147/downloads/paper-1.18.1-147.jar -O paper.jar
      - name: Download needed plugins
        run: |
          mkdir plugins && cd plugins
          wget -q https://dl.isurl.tech/StopServer.jar
          cp ../manhunt/ManHunt*.jar ./
          cd ..
      - name: Agree eula
        run: echo "eula=true" > eula.txt
      - name: Run the game
        run: java -Xms4G -Xmx6G -jar paper.jar --nogui
